services:
  whatsapp-finanzas:
    build: .
    container_name: whatsapp_finanzas_bot
    restart: always
    environment:
      - TZ=Europe/Madrid
      - DOCKER_ENV=true
    volumes:
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./presupuesto.json:/usr/src/app/presupuesto.json
      - ./estado.json:/usr/src/app/estado.json
      - ./logs.json:/usr/src/app/logs.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
